### ISSUE TITLE
Add companies & users advocacy

### ISSUE THREAD

**Issue by LudoGranger** [leadbay/landingpage#33]
1. companies advocacy 
> after 1st page, making sure it's part of the 1st page in the bottom
> subtitle "Built with sales in 200+ mid-market B2B companies"
> Logo "Backmarket, Actiondesk, Swile, bottle, fleet, alma, pennylane
3. users advocacy
> at the end of the last screen, before join
> "200+ B2B sales community waiting for the V1"
1. Louis Adam from ActionDesk: 'With current tools, it is now easy to launch new campaigns and close leads. However, it's not so easy to define my Ideal Customer Profile (ICP) and get a list of contacts ready to buy my product. That's why I am looking forward to adding Leadbay to my sales suite.'
2. Hugo De Villeplée from Backmarket: 'There are events we can't prevent, like the sales impact of the PS5 release. With Leadbay, I'll be able to predict those events and buy from the right suppliers, at the right time.'
3. Diane Roy from Bottle: 'Using my mail campaigns, I can't connect and close with my entire market. Leadbay will help me get in touch with the right leads at the right time.'
4. Sanja Zjalic from Bilobay: 'I want to see which leads came to my website, just as I can see which leads came to my LinkedIn account.

**Comment by LudoGranger** [comment]
<img width="894" alt="Screenshot 2023-06-19 at 08 56 41" src="https://github.com/leadbay/landingpage/assets/132485359/005e0110-6d86-43fe-b394-74082b012fc1">
<img width="1014" alt="Screenshot 2023-06-19 at 08 56 50" src="https://github.com/leadbay/landingpage/assets/132485359/31beb037-7c29-4341-bb98-4e2e9ddc11c6">
<img width="1283" alt="Screenshot 2023-06-19 at 08 57 12" src="https://github.com/leadbay/landingpage/assets/132485359/539b1629-b797-4531-9177-ac55d6872f29">

some example

**Comment by milstan** [comment]
done and merged
