### ISSUE TITLE
Feat: Redesign Landing

### ISSUE THREAD

**Issue by tristanremy** [leadbay/landingpage#43]
# Goals 
- Visualy more appealing and paving the way for new design line
- Better UX
- Better SEO and other tech. metrics

# Sub-tasks
- [x] #38 
- [x] #39
- [x] #40  
- [x] #41 
- [x] #42 
- [x] #45  
- [x] #46
- [x] #47 
- [x] #48

**Comment by LudoGranger** [comment]
@tristanremy https://www.loom.com/share/b95dae13bcb24053baf590e13661d88a?sid=0ed1dc93-443f-48cc-9ec5-9a5b67bc79da
